blog/urls.py
from django.conf.urls import url
from . import views
app_name = 'blog'

urlpatterns = [
	url(r'^sendmail/',views.sendmail),
	url(r'^index_send_email/',views.index,name = 'sendmail'),
	url(r'^$',views.IndexView.as_view(),name = 'index'),
	url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name = 'detail'),
	url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
]

comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name = 'post_comment'),
]

myblogweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'',include('uploadimg.urls',namespace='upload')),
    url(r'',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'',include('comments.urls')),
]

uploadimg/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^upload',views.upload_imgs,name='upload_imgs'),
	url(r'^Gallery.*?',views.IndexView.as_view(),name='upload'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import markdown
from django.utils.html import strip_tags
#分类
class Category(models.Model):
	name = models.CharField(max_length=20)
	def __str__(self):
		return self.name
class Test(models.Model):
	name = models.CharField(max_length=50)

class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	abstract = models.CharField(max_length=100,blank=True)
	#文章分类
	category = models.ForeignKey(Category)
	#阅读量
	views = models.PositiveIntegerField(default=0)
	def __str__(self):
		return self.title
	#跳转详情页
	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'pk':self.pk})
	#文章摘要
	def save(self,*args,**kwargs):
		if not self.abstract:
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
			])
			self.abstract = strip_tags(md.convert(self.content))[:50]
		super(Post,self).save(*args,**kwargs)
	#文章阅读量
	def increase_views(self):
		#浏览量+1
		self.views += 1
		#更新浏览量,覆写save方法
		self.save(update_fields=['views'])



# Create your models here.

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Comment(models.Model):
	name = models.CharField(max_length=20)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey('blog.Post')
	def __str__(self):
		return self.text[:20]

# Create your models here.

uploadimg/models.py
from django.db import models
from django.core.urlresolvers import reverse
class IMG(models.Model):
	img = models.ImageField(upload_to='uploadimg')
	name = models.CharField(max_length=200,blank=True)
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = '图片-사진'

# Create your models here.

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['name','text']

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Category
from django.views.generic import ListView
import markdown
from comments.forms import CommentForm
from django.core.mail import send_mail
from django.http import HttpResponse

# def index(request):
# 	post_list = Post.objects.all()
# 	return render(request,'blog/Temp/index.html',{'post_list':post_list})
#类视图
class IndexView(ListView):
	model = Post
	template_name = 'blog/Temp/post.html'
	context_object_name = 'post_list'
	paginate_by = 3
def category(request,pk):
	cate = get_object_or_404(Category,pk=pk)
	post_list = Post.objects.filter(category=cate).order_by('-id')
	return render(request,'blog/Temp/post.html',{'post_list':post_list})

def detail(request,pk):
	post = get_object_or_404(Post,pk=pk)
	post.increase_views()
	post.content = markdown.markdown(post.content,
	                                 extensions=[
		                                 'markdown.extensions.extra',
		                                 'markdown.extensions.codehilite',
		                                 'markdown.extensions.toc',
	                                 ])
	form = CommentForm()
	comment_list = post.comment_set.all()
	context = {
		'post':post,
		'form':form,
		'comment_list':comment_list
	}
	return render(request,'blog/Temp/blog.html',context=context)
#发邮件
def index(request):
	return render(request,'sendemail/send_email.html')

def sendmail(request):
	if request.POST:
		email_title = request.POST.get('Title')
		email_body = request.POST.get('Content')
		email = request.POST.get('ToEmail')
		EMAIL_FROM = '447724352@qq.com'
		send_status = send_mail(email_title,email_body,EMAIL_FROM,[email])
		if send_status:
			return HttpResponse('Success')
		else:
			return HttpResponse('Error')
	else:return render(request,'sendemail/send_email.html')
# Create your views here.

comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
#从blog模型中导入Post--联系文章
from blog.models import Post
#从自身模型中导入Comment--保存评论
from .models import Comment
#从表单模型中导入CommentForm--设置表单
from .forms import CommentForm

def post_comment(request,post_pk):
	#接收请求和参数
	#从Post表里按post_pk获得文章
	post = get_object_or_404(Post,pk=post_pk)
	#如果是post方法,需要处理表单数据（if this is a POST request we need to process the form data）
	if request.method == 'POST':
		#根据请求数据实例化表单（create a form instance and populate it with data form the request）
		form = CommentForm(request.POST)
		#如果表单数据合法
		if form.is_valid():
			#保存表单数据到comment,commit:仅仅实例化，并不保存到数据库
			comment = form.save(commit=False)
			#关联评论和文章
			comment.post = post
			#保存评论
			comment.save()
			#重定向到post的详情页
			return redirect(post)
		else:
			comment_list = post.comment_set.all()
			context = {
				'post':post,
				'form':form,
				'comment_list':comment_list
			}
			return render(request,'blog/Temp/blog.html',context=context)
		return redirect(post)

uploadimg/views.py
from django.shortcuts import render
from .models import IMG
from django.views.generic import ListView

class IndexView(ListView):
	model = IMG
	template_name = 'blog/Temp/Gallery.html'
	context_object_name = 'imgs'
	paginate_by = 12
def upload_imgs(request):
	if request.method == 'POST':
		new_img = IMG(img=request.FILES.get('img'),name=request.FILES.get('img').name)
		new_img.save()
	return render(request,'uploadimg/upload.html')
# Create your views here.

templates/blog/Temp/Gallery.html
{% extends 'blog/Temp/index.html' %}
{% block img %}

<ul>
    {% for img in imgs %}
    <li style="float: left">
        <div style="width: 200px;height: 150px;margin: 2px">
        <img src="{{ img.img.url }}" style="width:200px; height:150px">
            </div>
    </li>
    {% empty %}
    暂未上传图片
    {% endfor %}
</ul>
{% endblock img %}

templates/blog/Temp/blog.html
{% extends 'blog/Temp/index.html' %}
{% block detail %}
					<article>
						<div class="heading">
							<h2>{{post.title}}</h2>
						</div>
						<div class="content">
							{{post.content|safe}}
						</div>
						<div class="info">
							<p>By {{post.author}} on {{post.created_time}} - {{post.views}} Views</p>
						</div>
							<form action = "{% url 'comments:post_comment' post.pk %}" method = "post" class = "comment-form">
								{% csrf_token %}
								<div class="row">
									<div class="col-md-4">
										<label for="{{ form.name.id_for_label }}">名字:</label>
										{{ form.name }}
										{{ form.name.errors }}
									</div>
									<div>
										<label for="{{ form.text.id_for_label }}">评论:</label>
										{{ form.text }}
										{{ form.text.errors }}
										<button type = "submit" class="comment-btn">发布</button>
									</div>
								</div>
							</form>
						<div>
							<h3>评论列表：共 {{post.comment_set.count}} 条评论</h3>
							<ul>
								{% for comment in comment_list %}
								<li>
									<span>
										{{comment.name}}
									</span>
									<time>
										于 {{comment.created_time}} 发布：
									</time>
									<div>
										{{comment.text}}
									</div>
								</li><br>
								{% empty %}
								暂无评论
								{% endfor %}
							</ul>
						</div>
					</article>
{% endblock detail%}

templates/blog/Temp/index.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Solover</title>

	
    <!-- Mobile Specific Metas
  ================================================== -->

    
    <!-- CSS
  ================================================== -->
  	<link rel="stylesheet" href="{% static 'blog/css/zerogrid.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/responsive.css' %}">
	
	<!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="{% static 'blog/js/html5.js' %}"></script>
		<script src="{% static 'blog/js/css3-mediaqueries.js' %}"></script>
	<![endif]-->
	
	<link href="{% static 'blog/images/48.ico' %}" rel='icon' type='image/x-icon'/>

</head>

<body>
<div class="wrap-body zerogrid">
<!--------------Header--------------->
<header>
	<div class="wrap-header">

		<div class="top">
			<div class="socials">
			<ul>
				<!--
					<li><a href="#" title="facebook"><img  src="images/socials/facebook-32x32.png"/></a></li>
					<li><a href="#" title="google"><img  src="images/socials/google-32x32.png"/></a></li>
					<li><a href="#" title="twitter"><img  src="images/socials/twitter-32x32.png"/></a></li>
					<li><a href="#" title="rss"><img  src="images/socials/rss-32x32.png"/></a></li>
					<li><a href="#" title="youtube"><img  src="images/socials/youtube-32x32.png"/></a></li>
				-->
				</ul>
			</div>
			<!--
			<div id="search">
				<div class="button-search"></div>
				<input type="text" value="Search..." onFocus="if (this.value == &#39;Search...&#39;) {this.value = &#39;&#39;;}" onBlur="if (this.value == &#39;&#39;) {this.value = &#39;Search...&#39;;}">
			</div>
			-->
		</div>
		
		<div id="logo">
			<a href="{% url 'blog:index' %}"><h1>Solover</h1></a>
			<p>开始于9/13</p>
		</div>
		
		<nav>
			<div class="wrap-nav">
				<div class="menu">
					<ul>
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:index' %}">Blog</a></li>
						<li><a href="{% url 'upload:upload' %}">Gallery</a></li>
						<li><a href="{% url 'blog:index' %}">About</a></li>
						<li><a href="{% url 'blog:index' %}">Contact</a></li>
					</ul>
				</div>
			</div>
		</nav>
		
	</div>
</header>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/"  title="网站模板">网站模板</a></div>
<!--------------Content--------------->
<section id="content">
	<div class="wrap-content">
		<div class="row block">
			<div id="main-content" class="col-2-3">
				<div class="wrap-col">
					{% block img %}
					{% endblock img %}
					{% block post %}
					<!--
					{% for post in post_list %}
					<article>
						<div class="heading">
							<h2><a href="#">{{post.title}}</a></h2>
							<p>By {{post.author}} on {{post.created_time}} - <a href="#">01 Commnets</a></p>
						</div>
							<div class="content">

							<img src="images/img1.jpg" width="250px" height="100px"/>

							<p>&nbsp&nbsp{{post.content|truncatechars:50}}...</p>
							</div>
					</article>
					{% empty %}
					{% endfor %}
					-->
					{% endblock post%}
					{% block detail %}
					{% endblock detail %}
					{% if is_paginated %}
				<div class="pagination-simple" align="center" style="float: left; width: 600px;height: 30px;">
						{% if page_obj.has_previous %}
							<a href="?page={{page_obj.previous_page_number}}">上一页</a>
						{% endif %}
						<span class="current" >第 {{page_obj.number}} 页/共 {{paginator.num_pages}} 页</span>
						{% if page_obj.has_next %}
							<a href="?page={{page_obj.next_page_number}}">下一页</a>
						{% endif %}
				</div>
					{% endif %}
				</div>
			</div>
			<div id="sidebar" class="col-1-3">
				<div class="wrap-col">
					<div class="box">
						<div class="heading"><h2>关于</h2></div>
						<div class="content">
							该项目开始于2017/9/13,Django的实践项目。
							</div>
						</div>
					</div>
					<div class="box">
						<div class="heading"><h2>最近文章-최신문장</h2></div>
						{% get_recent_posts as new_posts%}
						<div class="content">
							{% for post in new_posts %}
							<li>
								<a href="{{post.get_absolute_url}}">{{post.title}}</a>
							</li>
							{% empty %}
							暂无发布
							{% endfor %}
						</div>
					</div>
					<div class="box">
						<div class="heading"><h2>分类-분류</h2></div>
						<div class="content">
							{% get_categories as category_list %}
							<ul>
								{% for category in category_list %}
								<li><a href="{% url 'blog:category' category.pk %}">{{category.name}}</a>({{category.num_posts}})</li>
								{% empty %}
								暂无分类
								{% endfor %}
							</ul>
						</div>
					</div>
				{% block upload %}
				{% endblock upload %}
				</div>
		</div>
	</div>
</section>
<!--------------Footer--------------->
<footer>
	<!--
	<div class="wrap-footer">
		<div class="row">
			<div class="col-1-3">
				<div class="wrap-col">
					<div class="box">
						<div class="heading"><h2>Image Gallery</h2></div>
						<div class="content gallery">
							<a href="#"><img src="images/img1.jpg" width="120"/></a>
							<a href="#"><img src="images/img2.jpg" width="120"/></a>
							<a href="#"><img src="images/img3.jpg" width="120"/></a>
							<a href="#"><img src="images/img4.jpg" width="120"/></a>
							<a href="#"><img src="images/img5.jpg" width="120"/></a>
							<a href="#"><img src="images/img1.jpg" width="120"/></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-1-3">
				<div class="wrap-col">
					<div class="box">
						<div class="heading"><h2>About Us</h2></div>
						<div class="content">
							<a href="#" target="_blank"><img src="images/zerotheme.jpg" style="border: 0px;"/></a>
							<p><a href="#" target="_blank">Free Html5 Templates</a> created by <a href="#">Zerotheme</a>. You can use and modify the template for both personal and commercial use. You must keep all copyright information and credit links in the template and associated files.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="col-1-3">
				<div class="wrap-col">
					<div class="box">
						<div class="heading"><h2>Contact Us</h2></div>
						<div class="content">
							<p>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue.</p>
							<p>Website : <a href="#" target="_blank">www.dglives.com</a></p>
							<p>+1 (123) 444-5677 <br/> +1 (123) 444-5678</p>
							<p>Address: 123 TemplateAccess Rd1</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	-->
	<div class="copyright">
		<p>Copyright © 2014 - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
	</div>
</footer>

</div>
</body></html>

templates/blog/Temp/post.html
{% extends 'blog/Temp/index.html' %}
{% block post %}
					{% for post in post_list %}
					<article>
						<div class="heading">
							<h2><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h2>
							<p>By {{post.author}} on {{post.created_time}} - {{post.views}} Views - {{post.comment_set.count}} Comments</p>
						</div>
							<div class="content">
							<p>&nbsp&nbsp{{post.abstract}}...</p>
							</div>
					</article>
					{% empty %}
					{% endfor %}
{% endblock post %}

templates/sendemail/send_email.html
<html>
<head>
    <title>QQ邮件发送</title>
</head>
<body>
<form method="post" action="/sendmail/" enctype="multipart/form-data">
    {% csrf_token %}
    发送到：<input type="email" name="ToEmail">
    标题：<input type="text" name="Title">
    内容：<input type="text" name = 'Content'>
    <input type="submit" value="发送">
</form>
</body>
</html>

templates/test.html
<!DOCTYPE>
<html lang="zh-CN">

    <head>
        <meta charset="utf-8">
        <title>
            上传图片
        </title>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js">
        </script>
        <script src="http://malsup.github.com/jquery.form.js">
        </script>

        <script type="text/javascript">
            (function() {

                $('#myform').ajaxForm({
                    success: function(data) {
                        var img = document.getElementById("preview_img");
                        img.src = data.imgurl;
                        img.style.display = 'block';
                    }
                });

            })();
        </script>

        <style>
            .Image {
                max-width:600px;height:auto;cursor:pointer;
                    border:1px dashed #4E6973;padding: 3px;
                    }
        </style>
    </head>

    <body>
        <form id="myform" action="/upload/uploadPic" method="post" enctype="multipart/form-data">
            <!-- {% csrf_token %} -->
            <input type="file" name="photo" id="image_upload" />
            <br>
            <input type="submit" value="上传" />
        </form>
        <img id="preview_img" src="" width="300" height="200" class="Image" style="display:none">
    </body>

</html>

templates/uploadimg/upload.html
<title>사진을 올리다--上传图片</title>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="img">
    <button type="submit">올리-上传</button>
</form>